// July Plan — Default seed data
import type {
  Section, Habit, RoutineBlock, WeeklyTheme, FinanceTarget,
} from './types';

const todayISO = () => new Date().toISOString().slice(0, 10);

export const DEFAULT_SECTIONS: Section[] = [
  {
    id: 'sec-health',
    name: 'Health',
    icon: 'Heart',
    color: '#ef4444',
    order: 1,
    subSections: [
      { id: 'sub-body', parentId: 'sec-health', name: 'Body' },
      { id: 'sub-mind', parentId: 'sec-health', name: 'Mind Focus' },
      { id: 'sub-skin', parentId: 'sec-health', name: 'Skin + Looks' },
      { id: 'sub-food', parentId: 'sec-health', name: 'Food / Nutrition' },
    ],
  },
  {
    id: 'sec-voice',
    name: 'Voice',
    icon: 'AudioLines',
    color: '#f97316',
    order: 2,
    subSections: [
      { id: 'sub-breathing', parentId: 'sec-voice', name: 'Breathing' },
      { id: 'sub-glides', parentId: 'sec-voice', name: 'Voice Glides' },
      { id: 'sub-twisters', parentId: 'sec-voice', name: 'Tongue Twisters' },
      { id: 'sub-cord', parentId: 'sec-voice', name: 'Cord Power' },
    ],
  },
  {
    id: 'sec-study',
    name: 'Study / Work',
    icon: 'Laptop',
    color: '#10b981',
    order: 3,
    subSections: [
      { id: 'sub-bca', parentId: 'sec-study', name: 'BCA Study' },
      { id: 'sub-coding', parentId: 'sec-study', name: 'Coding' },
      { id: 'sub-dsa', parentId: 'sec-study', name: 'DSA' },
      { id: 'sub-flutter', parentId: 'sec-study', name: 'Flutter' },
      { id: 'sub-projects', parentId: 'sec-study', name: 'Projects' },
      { id: 'sub-reading', parentId: 'sec-study', name: 'Reading / Learning' },
    ],
  },
  {
    id: 'sec-routine',
    name: 'Routine',
    icon: 'Sunrise',
    color: '#eab308',
    order: 4,
    subSections: [
      { id: 'sub-morning', parentId: 'sec-routine', name: 'Morning Routine' },
      { id: 'sub-office', parentId: 'sec-routine', name: 'Office Routine' },
      { id: 'sub-night', parentId: 'sec-routine', name: 'Night Routine' },
      { id: 'sub-breaks', parentId: 'sec-routine', name: 'Breaks / Reset' },
    ],
  },
  {
    id: 'sec-finance',
    name: 'Finance',
    icon: 'Wallet',
    color: '#22c55e',
    order: 5,
    subSections: [
      { id: 'sub-spend', parentId: 'sec-finance', name: 'Daily Spend' },
      { id: 'sub-goal', parentId: 'sec-finance', name: 'Monthly Goal' },
      { id: 'sub-savings', parentId: 'sec-finance', name: 'Savings Target' },
      { id: 'sub-future', parentId: 'sec-finance', name: 'Future Purchases' },
    ],
  },
  {
    id: 'sec-weekly',
    name: 'Weekly Plan',
    icon: 'CalendarDays',
    color: '#06b6d4',
    order: 6,
    subSections: [
      { id: 'sub-w1', parentId: 'sec-weekly', name: 'Week 1' },
      { id: 'sub-w2', parentId: 'sec-weekly', name: 'Week 2' },
      { id: 'sub-w3', parentId: 'sec-weekly', name: 'Week 3' },
      { id: 'sub-w4', parentId: 'sec-weekly', name: 'Week 4' },
    ],
  },
  {
    id: 'sec-monthly',
    name: 'Monthly Plan',
    icon: 'Target',
    color: '#8b5cf6',
    order: 7,
    subSections: [
      { id: 'sub-july', parentId: 'sec-monthly', name: 'July Goals' },
    ],
  },
  {
    id: 'sec-growth',
    name: 'Personal Growth',
    icon: 'TrendingUp',
    color: '#ec4899',
    order: 8,
    subSections: [
      { id: 'sub-confidence', parentId: 'sec-growth', name: 'Confidence' },
      { id: 'sub-discipline', parentId: 'sec-growth', name: 'Discipline' },
      { id: 'sub-brain', parentId: 'sec-growth', name: 'Brain Training' },
      { id: 'sub-consistency', parentId: 'sec-growth', name: 'Consistency' },
    ],
  },
];

// Priority order — drives UI sort across the app
export const PRIORITY_ORDER = [
  'Sleep', 'Nutrition', 'Workout', 'Study / Office / Work',
  'Mind training', 'Voice training', 'Looks / Skincare', 'Finance tracking',
];

export const DEFAULT_HABITS: Habit[] = [
  { id: 'h1', name: 'Wake up at 6:00 AM', category: 'Routine', target: 'daily', isActive: true, log: {} },
  { id: 'h2', name: 'Home workout', category: 'Health', target: 'daily', isActive: true, log: {} },
  { id: 'h3', name: 'Meditation', category: 'Mind', target: 'daily', isActive: true, log: {} },
  { id: 'h4', name: 'Voice training', category: 'Voice', target: 'daily', isActive: true, log: {} },
  { id: 'h5', name: 'Coding / Study', category: 'Study', target: 'daily', isActive: true, log: {} },
  { id: 'h6', name: 'Brain exercise', category: 'Mind', target: 'daily', isActive: true, log: {} },
  { id: 'h7', name: 'Healthy diet', category: 'Health', target: 'daily', isActive: true, log: {} },
  { id: 'h8', name: '3L+ water', category: 'Health', target: 'daily', isActive: true, log: {} },
  { id: 'h9', name: 'Skincare (AM + PM)', category: 'Looks', target: 'daily', isActive: true, log: {} },
  { id: 'h10', name: 'Sleep by 12:00 AM', category: 'Sleep', target: 'daily', isActive: true, log: {} },
];

// The full daily routine template from the spec, 6:00 AM → 12:00 AM
export const DEFAULT_ROUTINE: RoutineBlock[] = [
  {
    id: 'r1', title: 'Wake up + Freshen',
    startTime: '06:00', endTime: '06:15',
    category: 'sleep',
    description: '500–700 ml water · fresh air · 5 min sunlight · bed set',
    checklistItems: ['Drink 500-700 ml water', 'Get fresh air', '5 min sunlight', 'Make the bed'],
    log: {},
  },
  {
    id: 'r2', title: 'Home Workout',
    startTime: '06:15', endTime: '07:00',
    category: 'health',
    description: '5 min warm-up · 35 min strength · 5 min stretching',
    checklistItems: ['5 min warm-up', '35 min strength training', '5 min stretching'],
    log: {},
  },
  {
    id: 'r3', title: 'Mind Training',
    startTime: '07:00', endTime: '07:20',
    category: 'mind',
    description: '10 min meditation · 10 min breathing + gratitude',
    checklistItems: ['10 min meditation', '10 min breathing + gratitude'],
    log: {},
  },
  {
    id: 'r4', title: 'Bath + Grooming',
    startTime: '07:20', endTime: '07:45',
    category: 'looks',
    description: 'Face wash · moisturizer · sunscreen · hair care · oral hygiene',
    checklistItems: ['Face wash', 'Moisturizer', 'Sunscreen', 'Hair care', 'Oral hygiene'],
    log: {},
  },
  {
    id: 'r5', title: 'Healthy Breakfast',
    startTime: '07:45', endTime: '08:15',
    category: 'food',
    description: 'Eggs/paneer/soya · oats/poha · banana · milk',
    checklistItems: ['Eggs / paneer / soya', 'Oats / poha', 'Banana', 'Milk'],
    log: {},
  },
  {
    id: 'r6', title: 'Voice Training',
    startTime: '08:15', endTime: '08:30',
    category: 'voice',
    description: 'Deep breathing · humming · lip trills · tongue twisters · loud reading',
    checklistItems: ['Deep breathing', 'Humming', 'Lip trills', 'Tongue twisters', 'Loud reading'],
    log: {},
  },
  {
    id: 'r7', title: 'Programming / BCA Study',
    startTime: '08:30', endTime: '11:00',
    category: 'study',
    description: 'Coding · DSA · Flutter · BCA subjects',
    checklistItems: ['Coding', 'DSA', 'Flutter', 'BCA subjects'],
    log: {},
  },
  {
    id: 'r8', title: 'Break',
    startTime: '11:00', endTime: '11:20',
    category: 'break',
    description: 'Fruit · water · 5 min walk',
    checklistItems: ['Eat a fruit', 'Drink water', '5 min walk'],
    log: {},
  },
  {
    id: 'r9', title: 'Project / Learning',
    startTime: '11:20', endTime: '13:00',
    category: 'study',
    description: 'Build projects · reading · practice',
    checklistItems: ['Build projects', 'Reading', 'Practice'],
    log: {},
  },
  {
    id: 'r10', title: 'Lunch',
    startTime: '13:00', endTime: '13:30',
    category: 'food',
    description: 'Rice/roti · dal · sabzi · protein · salad',
    checklistItems: ['Rice / roti', 'Dal', 'Sabzi', 'Paneer / chicken / soya', 'Salad'],
    log: {},
  },
  {
    id: 'r11', title: 'Power Nap',
    startTime: '13:30', endTime: '14:00',
    category: 'break',
    description: '20–30 min nap',
    checklistItems: ['20-30 min nap'],
    log: {},
  },
  {
    id: 'r12', title: 'Brain Training',
    startTime: '14:00', endTime: '15:00',
    category: 'mind',
    description: 'Chess · memory · mental math · reading · critical thinking',
    checklistItems: ['Chess', 'Memory exercises', 'Mental math', 'Reading', 'Critical thinking'],
    log: {},
  },
  {
    id: 'r13', title: 'Looks Improvement',
    startTime: '15:00', endTime: '15:30',
    category: 'looks',
    description: 'Posture · smile · eye contact · walking style · dressing',
    checklistItems: ['Posture', 'Smile practice', 'Eye contact', 'Walking style', 'Dressing / grooming'],
    log: {},
  },
  {
    id: 'r14', title: 'Healthy Snack',
    startTime: '15:30', endTime: '16:00',
    category: 'food',
    description: 'Milk · banana · peanuts / dry fruits',
    checklistItems: ['Milk', 'Banana', 'Peanuts / dry fruits'],
    log: {},
  },
  {
    id: 'r15', title: 'Free Time / Family',
    startTime: '16:00', endTime: '17:15',
    category: 'break',
    description: 'Small tasks · hobby · relaxation',
    checklistItems: ['Small tasks', 'Hobby time', 'Relaxation'],
    log: {},
  },
  {
    id: 'r16', title: 'Freshen Up',
    startTime: '17:15', endTime: '17:45',
    category: 'looks',
    description: 'Face wash · change clothes · office prep',
    checklistItems: ['Face wash', 'Change clothes', 'Office preparation'],
    log: {},
  },
  {
    id: 'r17', title: 'Office Work',
    startTime: '18:00', endTime: '23:00',
    category: 'office',
    description: 'Every 60–90 min: water · 2 min walk · eye relaxation · neck stretch',
    checklistItems: ['Office work', 'Water breaks every 60-90 min', '2 min walk breaks', 'Eye relaxation', 'Neck stretch'],
    log: {},
  },
  {
    id: 'r18', title: 'Dinner',
    startTime: '23:20', endTime: '23:40',
    category: 'food',
    description: 'High-protein meal · light but filling',
    checklistItems: ['High-protein meal', 'Light but filling'],
    log: {},
  },
  {
    id: 'r19', title: 'Night Routine',
    startTime: '23:40', endTime: '23:55',
    category: 'looks',
    description: 'Face wash · moisturizer · lip balm · tomorrow top 3 · no phone',
    checklistItems: ['Face wash', 'Moisturizer', 'Lip balm', "Tomorrow's top 3 tasks", 'No phone before sleep'],
    log: {},
  },
  {
    id: 'r20', title: 'Sleep',
    startTime: '00:00', endTime: '06:00',
    category: 'sleep',
    description: 'Sleep on time · 6 hours minimum',
    checklistItems: ['Sleep by 12:00 AM'],
    log: {},
  },
];

export const DEFAULT_WEEKLY_THEMES: WeeklyTheme[] = [
  {
    week: 1,
    title: 'Build Habits',
    focus: ['Establish the routine', 'Daily workout', 'Daily meditation', 'Set work rhythm', 'Money / stability focus'],
  },
  {
    week: 2,
    title: 'Information Gathering',
    focus: ['Learn', 'Research', 'Collect references', 'Improve understanding'],
  },
  {
    week: 3,
    title: 'Plan → Confirm → Design → Future Plan',
    focus: ['Refine ideas', 'Finalize structure', 'Design future workflow'],
  },
  {
    week: 4,
    title: 'Gift / Financial Matrix',
    focus: ['Money tracking', 'Financial control', 'Future purchase planning', 'Savings matrix'],
  },
];

export const DEFAULT_FINANCE_TARGETS: FinanceTarget[] = [
  { id: 'ft1', title: 'Monthly Budget', amount: 5000, type: 'monthly' },
  { id: 'ft2', title: 'Weekly Cap', amount: 1200, type: 'monthly' },
  { id: 'ft3', title: 'Savings Target', amount: 12000, type: 'savings' },
  { id: 'ft4', title: 'Future Purchase Goal', amount: 50000, type: 'future' },
];

// Workout split — Sunday to Saturday
export const WEEKLY_WORKOUT_SPLIT: { day: string; focus: string }[] = [
  { day: 'Monday',    focus: 'Chest + Triceps + Core' },
  { day: 'Tuesday',   focus: 'Back + Biceps' },
  { day: 'Wednesday', focus: 'Legs' },
  { day: 'Thursday',  focus: 'Shoulders + Abs' },
  { day: 'Friday',    focus: 'Full Body' },
  { day: 'Saturday',  focus: 'Cardio + Mobility' },
  { day: 'Sunday',    focus: 'Stretching + Recovery' },
];

// Body exercise checklist seed — used by Health → Body section tasks
export const BODY_EXERCISES = [
  '10 Pushups',
  '20 Squats',
  '10 Leg Raises',
  'Bench Dips',
  '30 sec Hold',
  'Mountain Climbing',
];

// Default starter tasks — populated on first run only
export function defaultSeedTasks() {
  const today = todayISO();
  return [
    {
      id: 't-seed-1',
      title: 'Drink 3L water',
      sectionId: 'sec-health',
      subSectionId: 'sub-food',
      type: 'daily-recurring' as const,
      priority: 'critical' as const,
      status: 'pending' as const,
      startDate: today,
      time: undefined,
      reminderTime: '09:00',
      repeatRule: 'daily' as const,
      checklistItems: [],
      notes: 'Health priority #2 — Nutrition/Water',
      isTopPriority: true,
      createdAt: today,
      updatedAt: today,
      completionLog: {},
    },
    {
      id: 't-seed-2',
      title: 'Home Workout Session',
      sectionId: 'sec-health',
      subSectionId: 'sub-body',
      type: 'routine-block' as const,
      priority: 'high' as const,
      status: 'pending' as const,
      startDate: today,
      time: '06:15',
      reminderTime: '06:15',
      repeatRule: 'daily' as const,
      checklistItems: BODY_EXERCISES.map((text, i) => ({
        id: `cl-${i}`, text, done: false,
      })),
      notes: '5 min warm-up · 35 min strength · 5 min stretch',
      isTopPriority: true,
      createdAt: today,
      updatedAt: today,
      completionLog: {},
    },
    {
      id: 't-seed-3',
      title: 'Sleep by 12:00 AM',
      sectionId: 'sec-routine',
      subSectionId: 'sub-night',
      type: 'habit-item' as const,
      priority: 'critical' as const,
      status: 'pending' as const,
      startDate: today,
      time: '23:55',
      reminderTime: '23:30',
      repeatRule: 'daily' as const,
      checklistItems: [],
      notes: 'Health priority #1 — Sleep',
      isTopPriority: true,
      createdAt: today,
      updatedAt: today,
      completionLog: {},
    },
    {
      id: 't-seed-4',
      title: 'Meditation (10 min)',
      sectionId: 'sec-health',
      subSectionId: 'sub-mind',
      type: 'daily-recurring' as const,
      priority: 'high' as const,
      status: 'pending' as const,
      startDate: today,
      time: '07:00',
      repeatRule: 'daily' as const,
      checklistItems: [],
      isTopPriority: false,
      createdAt: today,
      updatedAt: today,
      completionLog: {},
    },
    {
      id: 't-seed-5',
      title: 'Voice Training Session',
      sectionId: 'sec-voice',
      subSectionId: 'sub-breathing',
      type: 'routine-block' as const,
      priority: 'medium' as const,
      status: 'pending' as const,
      startDate: today,
      time: '08:15',
      repeatRule: 'daily' as const,
      checklistItems: [
        { id: 'cl-v1', text: 'Deep belly breathing', done: false },
        { id: 'cl-v2', text: 'Humming', done: false },
        { id: 'cl-v3', text: 'Lip trills', done: false },
        { id: 'cl-v4', text: 'Tongue twisters', done: false },
        { id: 'cl-v5', text: 'Loud reading', done: false },
      ],
      isTopPriority: false,
      createdAt: today,
      updatedAt: today,
      completionLog: {},
    },
    {
      id: 't-seed-6',
      title: 'Programming / BCA Study',
      sectionId: 'sec-study',
      subSectionId: 'sub-coding',
      type: 'routine-block' as const,
      priority: 'high' as const,
      status: 'pending' as const,
      startDate: today,
      time: '08:30',
      repeatRule: 'daily' as const,
      checklistItems: [
        { id: 'cl-s1', text: 'Coding', done: false },
        { id: 'cl-s2', text: 'DSA', done: false },
        { id: 'cl-s3', text: 'Flutter', done: false },
        { id: 'cl-s4', text: 'BCA subjects', done: false },
      ],
      isTopPriority: true,
      createdAt: today,
      updatedAt: today,
      completionLog: {},
    },
    {
      id: 't-seed-7',
      title: 'Skincare — AM + PM',
      sectionId: 'sec-health',
      subSectionId: 'sub-skin',
      type: 'habit-item' as const,
      priority: 'medium' as const,
      status: 'pending' as const,
      startDate: today,
      repeatRule: 'daily' as const,
      checklistItems: [
        { id: 'cl-sk1', text: 'Facewash morning', done: false },
        { id: 'cl-sk2', text: 'Moisturizer morning', done: false },
        { id: 'cl-sk3', text: 'Facewash night', done: false },
        { id: 'cl-sk4', text: 'Lip balm', done: false },
      ],
      isTopPriority: false,
      createdAt: today,
      updatedAt: today,
      completionLog: {},
    },
    {
      id: 't-seed-8',
      title: 'Complete July Health Plan',
      sectionId: 'sec-monthly',
      subSectionId: 'sub-july',
      type: 'monthly-goal' as const,
      priority: 'high' as const,
      status: 'pending' as const,
      startDate: today,
      endDate: `${today.slice(0, 8)}31`,
      repeatRule: 'none' as const,
      checklistItems: [],
      isTopPriority: false,
      createdAt: today,
      updatedAt: today,
      completionLog: {},
    },
    {
      id: 't-seed-9',
      title: 'Save 5000 this month',
      sectionId: 'sec-finance',
      subSectionId: 'sub-savings',
      type: 'financial-goal' as const,
      priority: 'high' as const,
      status: 'pending' as const,
      startDate: today,
      endDate: `${today.slice(0, 8)}31`,
      repeatRule: 'none' as const,
      checklistItems: [],
      isTopPriority: false,
      createdAt: today,
      updatedAt: today,
      completionLog: {},
    },
    {
      id: 't-seed-10',
      title: 'Buy earphones',
      sectionId: 'sec-finance',
      subSectionId: 'sub-future',
      type: 'one-time' as const,
      priority: 'low' as const,
      status: 'pending' as const,
      startDate: today,
      repeatRule: 'none' as const,
      checklistItems: [],
      isTopPriority: false,
      createdAt: today,
      updatedAt: today,
      completionLog: {},
    },
  ];
}
